version: '3'
services:
  shell_charge_db:
    container_name: hacketeers_db
    image: postgres:13.3
    restart: on-failure
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"

#  shell-charge:
#    container_name: hacketeers
#    restart: on-failure
#    build: ./
#    tty: true
#    depends_on:
#         - shell_charge_db
#    ports:
#         - "8000:8000"
#    volumes:
#        - .:/opt/shell-charge/api
#    entrypoint:  dockerize -timeout 240s -wait tcp://shell_charge_db:5432 /opt/shell-charge/api/bin/startdev.sh


  redis:
    container_name: hacketeers-redis
    image: redis:alpine
    restart: on-failure
    ports:
      - "6379:6379"
