# Generated by Django 4.0.4 on 2022-09-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_alter_edge_source_alter_edge_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='custom_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='custom_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
